apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
#
images:
- name: goserver
  newName: odirleyrp/gitops
  newTag: 14420444ff781b099fef7394faf1003d09c286e4
